name: CI

on:
  push:
    branches:
      - main  # Specify the branch where you want tests to run

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'


      - name: Install dependencies
        run: pip install pygame

      - name: Install more dependencies
        run: pip install mock

      - name: Install even more dependencies
        run: pip install pyinstaller==3.6

      - name: Install xmllint
        run: sudo apt-get install -y python-dev

      - name: Run tests
        run: python test_sm.py  # Replace with your test command

      - name: Build Executable
        run: |
          # Replace with your build command
          pyinstaller --onefile contact_manager_solution.py
          # Create the "artifacts" directory if it doesn't exist
          mkdir -p artifacts
          # Move the executable to the "artifacts" directory
          mv dist/contact_manager_solution artifacts/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ContactManagerPython2
          path: artifacts
